### ISSUE TITLE
Add support for Yarn 2

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/buildpacks#150]
As requested in https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/318, we should enhance the Yarn buildpack to support Yarn v2. 

Currently if you try to build an app with a lockfile created by Yarn 2 you get an error like this: 

```
2021-08-26 21:02:42.052 CESTCloud FunctionsUpdateFunctioneurope-west1:my_functionhannes@my-email.com {@type: type.googleapis.com/google.cloud.audit.AuditLog, authenticationInfo: {…}, authorizationInfo: […], methodName: google.cloud.functions.v1.CloudFunctionsService.UpdateFunction, request: {…}, requestMetadata: {…}, resourceLocation: {…}, resourceName: projects/my-project/locations/europe-west…
2021-08-26 21:03:38.562 CESTmy_function Provided module can't be loaded.
2021-08-26 21:03:38.562 CESTmy_function Did you list all required modules in the package.json dependencies?
2021-08-26 21:03:38.562 CESTmy_function Detailed stack trace: Error: Cannot find module 'node-fetch'
2021-08-26 21:03:38.562 CESTmy_function Require stack:
2021-08-26 21:03:38.562 CESTmy_function - /workspace/src/lib/API/some_api.js
2021-08-26 21:03:38.562 CESTmy_function - /workspace/src/lib/my_function.js
2021-08-26 21:03:38.562 CESTmy_function - /workspace/src/index.js
2021-08-26 21:03:38.562 CESTmy_function - /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js
2021-08-26 21:03:38.562 CESTmy_function - /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/index.js
2021-08-26 21:03:38.562 CESTmy_function at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2021-08-26 21:03:38.562 CESTmy_function at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2021-08-26 21:03:38.562 CESTmy_function at Module.require (internal/modules/cjs/loader.js:974:19)
2021-08-26 21:03:38.562 CESTmy_function at require (internal/modules/cjs/helpers.js:92:18)
2021-08-26 21:03:38.562 CESTmy_function at Object.<anonymous> (/workspace/src/lib/API/some_api.js:36:15)
2021-08-26 21:03:38.562 CESTmy_function at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-08-26 21:03:38.562 CESTmy_function at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-08-26 21:03:38.562 CESTmy_function at Module.load (internal/modules/cjs/loader.js:950:32)
2021-08-26 21:03:38.562 CESTmy_function at Function.Module._load (internal/modules/cjs/loader.js:790:14)
2021-08-26 21:03:38.562 CESTmy_function at Module.require (internal/modules/cjs/loader.js:974:19)
2021-08-26 21:03:38.563 CESTmy_function Could not load the function, shutting down.}
```

Currently, yarn is installed in our base images. We may need to take a hint from the `package.json` engines field to install the correct version: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

**Comment by briandealwis** [comment]
See also #107
