### ISSUE TITLE
Failed to detect Python function

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpacks#19]
Reporting some friction I encountered adopting this. I went to https://cloud.google.com/functions/docs/quickstart-python

copied this to `func.py`:

```
def hello_world(request):
    """Responds to any HTTP request.
    Args:
        request (flask.Request): HTTP request object.
    Returns:
        The response text or any set of values that can be turned into a
        Response object using
        `make_response <http://flask.pocoo.org/docs/1.0/api/#flask.Flask.make_response>`.
    """
    request_json = request.get_json()
    if request.args and 'message' in request.args:
        return request.args.get('message')
    elif request_json and 'message' in request_json:
        return request_json['message']
    else:
        return f'Hello World!'
```

then created `requirements.txt` with just `Flask` in it.

Then set the default builder to google's and ran:

```
GOOGLE_FUNCTION_TARGET=hello_world pack build gcr.io/ahmetb-demo/myfunc
```

```
===> DETECTING
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
ERROR: failed with status code: 6
```

I am guessing documentation on how to structure functions is missing from the readme. File name might be the culprit?

**Comment by ahmetb** [comment]
Similarly I cloned the Functions Framework Python example
https://github.com/GoogleCloudPlatform/functions-framework-python/tree/master/examples/cloud_run_http and also doesn't work and fails with the same error.

**Comment by ahmetb** [comment]
It would be somewhat cool to have `--verbose` on these steps (maybe by setting GOOGLE_DEBUG=1). This has been my biggest pain point about CNCF Buildpacks (and also why I always kept trying and ran away from it). There's very little visibility.

Anything you can do to answer users’ "but whyyyy? what is it doing under the covers to fail to detect?" can help users tremendously to self-serve.

**Comment by di** [comment]
The first issue here is that you need to pass the environment variable into `pack` instead -- it doesn't inherit the environment variables from where it's ran:

```
$ pack build --env GOOGLE_FUNCTION_TARGET=hello_world test
latest: Pulling from buildpacks/builder
Digest: sha256:dc4892caa054a61d26ab4403bb87184285ef094b2763b6563cb69468d8a9cef9
Status: Image is up to date for gcr.io/buildpacks/builder:latest
latest: Pulling from buildpacks/gcp/run
Digest: sha256:3ad752a1ce30d7c343c805b451d52d4fb6d523e35c587c245d6aad0830979979
Status: Image is up to date for gcr.io/buildpacks/gcp/run:latest
===> DETECTING
[detector] 2 of 4 buildpacks participating
[detector] google.python.runtime             0.9.0
[detector] google.python.functions-framework 0.9.0
===> ANALYZING
[analyzer] Restoring metadata for "google.python.runtime:python" from app image
[analyzer] Restoring metadata for "google.python.functions-framework:functions-framework" from app image
===> RESTORING
[restorer] Restoring data for "google.python.runtime:python" from cache
[restorer] Restoring data for "google.python.functions-framework:functions-framework" from cache
===> BUILDING
[builder] === Python - Runtime (google.python.runtime@0.9.0) ===
[builder] Using latest runtime version: 3.8.2
[builder] === Python - Functions Framework (google.python.functions-framework@0.9.0) ===
[builder] Handling functions without dependency on functions-framework.
[builder] Dependencies cache hit, skipping installation.
[builder] ————————————————————————————————————————————————————————————————————————————————
[builder] Running "python3 -m compileall ."
[builder] Listing '.'...
[builder] Compiling './func.py'...
[builder] Done "python3 -m compileall ." (222.0063ms)
===> EXPORTING
[exporter] Reusing layer 'launcher'
[exporter] Adding layer 'google.python.runtime:python'
[exporter] Reusing layer 'google.python.functions-framework:functions-framework'
[exporter] Adding 1/1 app layer(s)
[exporter] Reusing layer 'config'
[exporter] *** Images (b6f3d9da4ee8):
[exporter]       index.docker.io/library/test:latest
[exporter] Adding cache layer 'google.python.runtime:python'
[exporter] Reusing cache layer 'google.python.functions-framework:functions-framework'
Successfully built image test
```

If you had done that, it would have built an image, but the image would have failed to run:

```
$ docker run -p8080:8080 test
Traceback (most recent call last):
  File "/layers/google.python.functions-framework/functions-framework/bin/functions-framework", line 10, in <module>
    sys.exit(_cli())
  File "/layers/google.python.functions-framework/functions-framework/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/layers/google.python.functions-framework/functions-framework/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/layers/google.python.functions-framework/functions-framework/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/layers/google.python.functions-framework/functions-framework/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/layers/google.python.functions-framework/functions-framework/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/layers/google.python.functions-framework/functions-framework/functions_framework/__init__.py", line 130, in create_app
    raise MissingSourceException(
functions_framework.exceptions.MissingSourceException: File /workspace/main.py that is expected to define function doesn't exist
```

Which should indicate that you need to rename `func.py` to `main.py`. (You could also set `GOOGLE_FUNCTION_SOURCE=func.py`, but I'm not sure that should be exposed here.)

I think at the very least the buildpack should ensure `GOOGLE_FUNCTION_SOURCE` actually exists.

**Comment by ahmetb** [comment]
> The first issue here is that you need to pass the environment variable into `pack` instead -- it doesn't inherit the environment variables from where it's ran:

this was it! Thanks Dustin.

**Comment by ahmetb** [comment]
GOOGLE_FUNCTION_SOURCE is not documented fwiw.

**Comment by lukasberger** [comment]
> It would be somewhat cool to have --verbose on these steps (maybe by setting GOOGLE_DEBUG=1). This has been my biggest pain point about CNCF Buildpacks (and also why I always kept trying and ran away from it). There's very little visibility.

There is in fact a `--verbose` flag on pack which prints all the detection steps and why something opted in/out. Most of our buildpacks opt-out with a message.
