### ISSUE TITLE
Command 'krb5-config --libs gssapi' returned non-zero exit status 127

### ISSUE THREAD

**Issue by rushourllc** [GoogleCloudPlatform/buildpacks#253]
Getting this error on Cloud Run for a Django app deploy, it appears to be at OS level dependencies:

```Collecting gssapi
Step #0 - "Buildpack":   Downloading gssapi-1.8.2.tar.gz (94 kB)
Step #0 - "Buildpack":      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.3/94.3 kB 17.3 MB/s eta 0:00:00
Step #0 - "Buildpack":   Installing build dependencies: started
Step #0 - "Buildpack":   Installing build dependencies: finished with status 'done'
Step #0 - "Buildpack":   Getting requirements to build wheel: started
Step #0 - "Buildpack":   Getting requirements to build wheel: finished with status 'error'
Step #0 - "Buildpack":   error: subprocess-exited-with-error
Step #0 - "Buildpack":   
Step #0 - "Buildpack":   × Getting requirements to build wheel did not run successfully.
Step #0 - "Buildpack":   │ exit code: 1
Step #0 - "Buildpack":   ╰─> [21 lines of output]
Step #0 - "Buildpack":       /bin/sh: 1: krb5-config: not found
Step #0 - "Buildpack":       Traceback (most recent call last):
Step #0 - "Buildpack":         File "/layers/google.python.runtime/python/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
Step #0 - "Buildpack":           main()
Step #0 - "Buildpack":         File "/layers/google.python.runtime/python/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
Step #0 - "Buildpack":           json_out['return_val'] = hook(**hook_input['kwargs'])
Step #0 - "Buildpack":         File "/layers/google.python.runtime/python/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
Step #0 - "Buildpack":           return hook(config_settings)
Step #0 - "Buildpack":         File "/tmp/pip-build-env-tn84vi3f/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
Step #0 - "Buildpack":           return self._get_build_requires(config_settings, requirements=['wheel'])
Step #0 - "Buildpack":         File "/tmp/pip-build-env-tn84vi3f/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
Step #0 - "Buildpack":           self.run_setup()
Step #0 - "Buildpack":         File "/tmp/pip-build-env-tn84vi3f/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
Step #0 - "Buildpack":           exec(code, locals())
Step #0 - "Buildpack":         File "<string>", line 109, in <module>
Step #0 - "Buildpack":         File "<string>", line 22, in get_output
Step #0 - "Buildpack":         File "/layers/google.python.runtime/python/lib/python3.7/subprocess.py", line 395, in check_output
Step #0 - "Buildpack":           **kwargs).stdout
Step #0 - "Buildpack":         File "/layers/google.python.runtime/python/lib/python3.7/subprocess.py", line 487, in run
Step #0 - "Buildpack":           output=stdout, stderr=stderr)
Step #0 - "Buildpack":       subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
Step #0 - "Buildpack":       [end of output]
Step #0 - "Buildpack":   
Step #0 - "Buildpack":   note: This error originates from a subprocess, and is likely not a problem with pip.
Step #0 - "Buildpack": error: subprocess-exited-with-error
Step #0 - "Buildpack": 
Step #0 - "Buildpack": × Getting requirements to build wheel did not run successfully.
Step #0 - "Buildpack": │ exit code: 1
Step #0 - "Buildpack": ╰─> See above for output.
Step #0 - "Buildpack": 
Step #0 - "Buildpack": note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by rushourllc** [comment]
Resolved with docker setup

**Comment by FaCoffee1984** [comment]
@rushourllc what setup? I am seeing this error as I try to deploy to my Azure Function (Python 3.9) using my yaml pipeline. I am not using Docker myself, but maybe Azure Functions are using it?

**Comment by waqarakbar** [comment]
I got the same error on ubuntu 22.04 with python 3.10 and trying to install airflow 2.9.0
Installing the **libkrb5-dev** and via apt fixed my problem

**sudo apt-get update
sudo apt-get install -y libkrb5-dev**
