### ISSUE TITLE
Python build cannot complete when pulling requirements from a private pypi artifact registry

### ISSUE THREAD

**Issue by kkoscianski** [GoogleCloudPlatform/buildpacks#297]
When using --extra-index in the requirements.txt file the following error is observed. The service account for cloud build has the appropriate permissions attached to allow repository administration. It appears that credentials are not being generated for the build container.

`pack build us-central1-docker.pkg.dev/<PROJECT_ID>/<REPO_ID>/pack-test --builder="gcr.io/buildpacks/builder:google-22" --publish="true" -v`

```User for us-central1-python.pkg.dev: ERROR: Exception:
Traceback (most recent call last):
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
    for version, func in infos:
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 279, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 890, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 831, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 791, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 461, in fetch_response
    return _get_index_content(location, session=self.session)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 364, in _get_index_content
    resp = _get_simple_response(url, session=session)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 135, in _get_simple_response
    resp = session.get(
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/network/session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 708, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_vendor/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/network/auth.py", line 388, in handle_401
    username, password, save = self._prompt_for_password(parsed.netloc)
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/network/auth.py", line 351, in _prompt_for_password
    username = ask_input(f"User for {netloc}: ")
  File "/layers/google.python.runtime/python/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 205, in ask_input
    return input(message)
EOFError: EOF when reading a line
```

**Comment by jama22** [comment]
Looks like you're trying to build your app locally with `pack` but pull in a remote dependency hosted on a private Python Artifact Registry. In that case, I think you'll have to do a modified version of the steps for [Authenticating with a service account key](https://cloud.google.com/artifact-registry/docs/python/authentication#sa-key) in the AR docs. 

I haven't tried this myself yet, but once you get this set up you should be able to modify the repo url in `--extra-index` to include `username` and `password`

`--extra-index-url = https://_json_key_base64:KEY@LOCATION-python.pkg.dev/PROJECT/REPOSITORY/simple/`

The other approach, which i think is pretty painful, would be to somehow mount `.pypirc` in the `$HOME` directory of the builder.

FWIW, if you submit the build directly to Cloud Build instead of trying to build locally with pack, Cloud Build will take care of the authentication for you behind the scenes; but that might not meet the needs of your use case.

I think an interesting feature might be to let users bring their own `.pypirc` file so that they can easily override the config within the builder containers.

**Comment by kkoscianski** [comment]
Thanks for the response, the error posted was from building locally but it was a convenience as I was attempting to debug what was happening. Cloud Build runs into this issue as well, I have included a build log with the information in it.

Relevant Buildstep:
```
  - id: Pack
    #waitFor:
    #  - Pylint
    # - MyPy
    name: gcr.io/k8s-skaffold/pack
    args: ["build", "us-central1-docker.pkg.dev/<PROJECT_ID>/<REPO_NAME>/pack-test", "--builder=gcr.io/buildpacks/builder:google-22", "--publish=true"]
```
[cloud-buildpacks.log](https://github.com/GoogleCloudPlatform/buildpacks/files/11400402/cloud-buildpacks.log)

**Comment by jama22** [comment]
With Cloud Build you might have to go through the `gcloud` cli, try

`gcloud builds submit --pack image=us-central1-docker.pkg.dev/<PROJECT_ID>/<REPO_NAME>/pack-test`

https://cloud.google.com/docs/buildpacks/build-application#remote_builds

**Comment by kkoscianski** [comment]
Running through `gcloud` cli did work and will give me a way forward but triggering a cloud build process within a cloud build process is rather clunky. This is enough to get me through the block, thanks for the help.

**Comment by jama22** [comment]
Nice, glad that worked for you.

**Comment by runa** [comment]
@jama22 thanks for your comment, I found myself in the same situation as the OP, @kkoscianski 

If I have a step in the Cloud Build yaml using buildpack to build the app, the magic behind the scenes doesn't happen (I guess you're refering to [configuring netrc](https://github.com/GoogleCloudPlatform/buildpacks/blob/6fdff1342b3822d0d0d69fdc578aac34abc5b193/pkg/ar/ar.go#L128)) and I'm asked for the user name (and then, fails).

Remotely building from the gcloud CLI works

If I understood correctly, OP temporary solution is to launch a remote Cloud Build using the gcloud CLI from another Cloud Build?

I find this to be overkill and I was wondering if maybe I should file a bug report on this topic?

Thanks

**Comment by kkoscianski** [comment]
@runa I ultimately solved this issue later by simply adding `--network cloudbuild` to the arguments of pack. This allows the builder to use the workload identity provided to the pods cloud build is running on by allowing it to talk with the metadata server running on the GKE cluster google is managing.

**Comment by runa** [comment]
Thanks a lot! this is the correct answer <3

**Comment by jama22** [comment]
Hunh, interesting. Thanks for the followup as well @kkoscianski . I think I can amend our docs https://cloud.google.com/docs/buildpacks/build-application#build_with_configuration_files to include a reference to `--network cloudduild`
