### ISSUE TITLE
Cannot build with python package mysqlclient (setup.py egg_info did not run successfully)

### ISSUE THREAD

**Issue by fc-data** [GoogleCloudPlatform/buildpacks#364]
Using --builder=gcr.io/buildpacks/builder as per the tutorial, and tried multiple versions of mysqlclient but keeps failing. Same errors as with deploying via cloud run

**Comment by fc-data** [comment]
[builder] Collecting mysqlclient==1.4.6 (from -r requirements.txt (line 53))
[builder]   Downloading mysqlclient-1.4.6.tar.gz (85 kB)
[builder]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 kB 13.2 MB/s eta 0:00:00
[builder]   Preparing metadata (setup.py): started
[builder]   Preparing metadata (setup.py): finished with status 'error'
[builder]   error: subprocess-exited-with-error
[builder]
[builder]   × python setup.py egg_info did not run successfully.
[builder]   │ exit code: 1
[builder]   ╰─> [13 lines of output]
[builder]       /bin/sh: 1: mysql_config: not found
[builder]       /bin/sh: 1: mariadb_config: not found
[builder]       /bin/sh: 1: mysql_config: not found
[builder]       Traceback (most recent call last):
[builder]         File "<string>", line 2, in <module>
[builder]         File "<pip-setuptools-caller>", line 34, in <module>
[builder]         File "/tmp/pip-install-kzv0k6dk/mysqlclient_3a1883b6c312407ebd3be348ba36897a/setup.py", line 16, in <module>
[builder]           metadata, options = get_config()
[builder]         File "/tmp/pip-install-kzv0k6dk/mysqlclient_3a1883b6c312407ebd3be348ba36897a/setup_posix.py", line 61, in get_config
[builder]           libs = mysql_config("libs")
[builder]         File "/tmp/pip-install-kzv0k6dk/mysqlclient_3a1883b6c312407ebd3be348ba36897a/setup_posix.py", line 29, in mysql_config
[builder]           raise EnvironmentError("%!!(MISSING)s(MISSING) not found" %!!(MISSING)((MISSING)_mysql_config_path,))
[builder]       OSError: mysql_config not found
[builder]       [end of output]
