### ISSUE TITLE
I got these error when I try to run test on Cloud Function

### ISSUE THREAD

**Issue by jeeeepp** [GoogleCloudPlatform/buildpacks#368]
python 3.12
```
[2:22:11 PM] - Preparing function sources ...
[2:22:11 PM] - Building function sources ...
[2:22:13 PM] - Error: Command failed: cd /gcf-working-dir/function-sources && pack build gcf-ui-function --builder gcr.io/gae-runtimes/buildpacks/python/builder --pull-policy if-not-present --env GOOGLE_FUNCTION_TARGET=env_vars --env GOOGLE_FUNCTION_SIGNATURE_TYPE=http --env GOOGLE_DEVMODE=1 --env GOOGLE_RUNTIME_VERSION=3.12
[builder] === Python - Runtime (google.python.runtime@0.9.1) ===
[builder] layers path: /layers/google.python.runtime/python
[builder] Using Python version from GOOGLE_RUNTIME_VERSION: 3.12
[builder] 2023/11/29 07:22:13 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/python/version.json
[builder] Failure: (ID: afc8608d) invalid Python version specified: failed to resolve version matching: 3.12
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://cloud.google.com/docs/buildpacks/overview
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
[builder] --------------------------------------------------------------------------------
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at buildFunction (/app/app.runfiles/google3/cloud/console/web/functions/external/testing_server/workers/build_function_worker.js:17:38)
    at Object.<anonymous> (/app/app.runfiles/google3/cloud/console/web/functions/external/testing_server/workers/build_function_worker.js:35:131)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:183:24)
[builder] === Python - Runtime (google.python.runtime@0.9.1) ===
[builder] layers path: /layers/google.python.runtime/python
[builder] Using Python version from GOOGLE_RUNTIME_VERSION: 3.12
[builder] 2023/11/29 07:22:13 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/python/version.json
[builder] Failure: (ID: afc8608d) invalid Python version specified: failed to resolve version matching: 3.12
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://cloud.google.com/docs/buildpacks/overview
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
[builder] --------------------------------------------------------------------------------
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
[2:22:13 PM] - Error while building function sources. Please check logs.


#############################################################
#############################################################
```

Here is my source code
```
import os


def env_vars(request):
    return os.environ.get("FOO", "Specified environment variable is not set.")
```

**Comment by jeeeepp** [comment]
![Screenshot 2566-11-29 at 14 35 15](https://github.com/GoogleCloudPlatform/buildpacks/assets/100660569/c36e84fc-5c10-49f0-8d39-dc3a9614d1a1)

**Comment by shivamsaraswat** [comment]
Just change your service account to "App Engine Default Service Account" while setting Configuration. This solved my problem.

**Comment by eloi-jamao** [comment]
Same problem and tested solution proposed by @shivamsaraswat :

> Just change your service account to "App Engine Default Service Account" while setting Configuration. This solved my problem.

This works but this is not mentioned in a basic tutorial such as [this one](https://cloud.google.com/scheduler/docs/tut-pub-sub#create_a_with_a_trigger) and also it is against best practices. Is this normal?

**Comment by shivamsaraswat** [comment]
Cloud Function spins up the Cloud Run machine while running. So, using "App Engine Default Service Account" is ok in my opinion.

**Comment by jeeeepp** [comment]
Thank you @shivamsaraswat  It working now sorry for late replay
