### ISSUE TITLE
firebase AppHosting Fail to deploy ionic angular ssr app with Error: Unable to determine format for workspace path

### ISSUE THREAD

**Issue by pwejar** [GoogleCloudPlatform/buildpacks#423]
2024-06-18 12:25:33.721 EAT
Step #2: 
2024-06-18 12:25:33.721 EAT
Step #2: Error: Unable to determine format for workspace path.
2024-06-18 12:25:33.721 EAT
Step #2:     at Object.readWorkspace (/workspace/node_modules/@angular-devkit/core/src/workspace/core.js:86:15)
2024-06-18 12:25:33.721 EAT
Step #2:     at async checkStandaloneBuildConditions (file:///layers/google.nodejs.firebaseangular/npm_modules/node_modules/@apphosting/adapter-angular/dist/utils.js:33:27)
2024-06-18 12:25:33.721 EAT
Step #2:     at async file:///layers/google.nodejs.firebaseangular/npm_modules/node_modules/@apphosting/adapter-angular/dist/bin/build.js:29:5
2024-06-18 12:25:33.721 EAT
Step #2: 
2024-06-18 12:25:33.721 EAT
Step #2: Node.js v20.14.0
2024-06-18 12:25:33.750 EAT
Step #2: Done "npm exec --prefix /layers/google.nodejs.firebaseangular/npm_..." (1.028177006s)
2024-06-18 12:25:33.750 EAT
Step #2: --------------------------------------------------------------------------------
2024-06-18 12:25:33.750 EAT
Step #2: failed to build: (error ID: 2bbd27b1):
2024-06-18 12:25:33.750 EAT
Step #2: /workspace/node_modules/@angular-devkit/core/src/workspace/core.js:86
2024-06-18 12:25:33.750 EAT
Step #2:         throw new Error('Unable to determine format for workspace path.');

**Comment by Yuangwang** [comment]
Could you share the repo you're trying to deploy? That would be very helpful for reproducing and finding the issue
